### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Waqar-Younis** [haomateach/webdev#10]
INFO 1213 Section S13
Does the assignment needs to have only 2 pages or could there be more?

**Comment by mjensen341** [comment]
In the mandatory requirements section it says it needs to be exactly 2 pages, so i'd just follow that.

**Comment by haomateach** [comment]
@Waqar-Younis Just 2 pages. Please focus on the quality, not the quantity.

**Comment by Mehakdeepkaur4** [comment]
When will the results of quiz will be uploaded??
