### ISSUE TITLE
external CSS 

### ISSUE THREAD

**Issue by prabhjot2022** [haomateach/webdev#12]
web application development R10
Name - Prabhjot Preet Kaur
ID number- 100393983

I tried to link my file with the external html file. This doesn't works.  I am not getting where the syntax is. I have attached screenshots of my code for reference. 

![2020-09-23 (1)](https://user-images.githubusercontent.com/70991116/94092329-4d96af80-fdcf-11ea-8575-be628ea9db16.png)
![2020-09-23 (3)](https://user-images.githubusercontent.com/70991116/94092340-525b6380-fdcf-11ea-9543-21a2871f1c99.png)
![2020-09-23](https://user-images.githubusercontent.com/70991116/94092343-54bdbd80-fdcf-11ea-82f9-eb67f467f006.png)

**Comment by madmoney99** [comment]
You've named your css sheet 'styles.css' but you're calling 'style.css' in your index.html. 

Change one or the other and it should work.

**Comment by prabhjot2022** [comment]
> You've named your css sheet 'styles.css' but you're calling 'style.css' in your index.html.
> 
> Change one or the other and it should work.

Thank you @madmoney99  . It works now .
