### ISSUE TITLE
Assignment 1 

### ISSUE THREAD

**Issue by HafsahDurrani** [haomateach/webdev#15]
INFO 1213 S13
Hafsah Durrani 100213500

Hello Professor,
Would it be ok if for Assignment 1 I submit what I created while following along modules 4 and 5? I have customized and styled it differently from what Angela did in the tutorials.

Thank you.

**Comment by haomateach** [comment]
?I will make a announcement about this.


The deadline will be extended, just let you know in advance.



------------------------------------------------------------------------
Hao Ma, Ph.D., Faculty Member,
Department of Computer Science and Information Technology
School of Business, Kwantlen Polytechnic University
---------------------------------------------------------------------
________________________________

**Comment by madmoney99** [comment]
@haomateach So we don't need to worry about submitting Assignment 1 at this point?

**Comment by NumanSyed** [comment]
I have zip containing folder + txt - is this correct

**Comment by HafsahDurrani** [comment]
Thank you Professor, the week 3 review video answered a lot of my questions.

**Comment by HafsahDurrani** [comment]
Would it be ok if used a CSS button generator like in the udemy videos or not?

**Comment by haomateach** [comment]
@HafsahDurrani Yes!
