### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by Waqar-Younis** [haomateach/webdev#16]
INFO 1213
S13
Professor, I uploaded my website on GitHub and got the link, but the link does not open up my second page.  what do you think could be the possible solution?

**Comment by haomateach** [comment]
The link should only open up your homepage, and the homepage contains one hyperlink that can open up the second page. That's how it is organized.

**Comment by Waqar-Younis** [comment]
What I have done is I have made a button, that contains a hyperlink. So do u suggest I should totally remove the button and just have a link showing?

**Comment by haomateach** [comment]
No, I did not mean that. What you did is perfectly fine.

**Comment by NumanSyed** [comment]
your website link is waqar-younis.github.io/info1213a1/
you need your button to have the link  ...info1213a1/something.html
