### ISSUE TITLE
assignment 1

### ISSUE THREAD

**Issue by ppriya2** [haomateach/webdev#17]
hi, I'm Priya student id 100400760
my course and section are INFO1213 S13
@haomateach 
sir, can you please check my submission and let me know if their is any issue with my assignment.

**Comment by ppriya2** [comment]
Hi Sir, assignment first's work is going great. just wanna re-sure if my assignment is good and doesn't have any problem while being seen by you

**Comment by haomateach** [comment]
I believe I have emailed you regarding my concerns.
