### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by bbirlie** [haomateach/webdev#18]
Info 1213 S13

Hello,

I would like to include a background image for my cv site but I cant seem to get it to work even after reading online resources or the documentation. I want it included on my top div only and I have the image saved in an image folder attached to cv main folder. 

Tried using css:

background-image: url("../images/background.jpg");

the background does change but not to the image provided

**Comment by madmoney99** [comment]
What's the name of the background file you're using?  Is it background.jpg or is it something else?   What does the background change to?

I assume you have (something like this) this in your styles.css as a selector?
```
.mainbody {
   background-image: url("../images/nameoffile.PNG");
}
```

and the same is being called by the index.html?
```<div class="mainbody"> 

</div>```

Easier if you can post snippets of the code or if you've pushed them to github, then the code can be looked at for possible syntax errors.   Hope this helps.

Tony

**Comment by haomateach** [comment]
@bbirlie  What's your file hierarchy structure? That's very important. I suspect that the relative url you are using here  `../images/background.jpg` is incorrect.
