### ISSUE TITLE
css designing

### ISSUE THREAD

**Issue by Bhavjot102** [haomateach/webdev#19]
INFO 1213:Web Application Development(R10)
100394335
Css designing is not working for my github page. But otherwise it is working on a browser.

**Comment by madmoney99** [comment]
Your index.html file points at your CSS file assuming it's inside a folder ```css/styles.css```

Either put that styles.css inside a folder named CSS or remove the css from the front of the call in the index file. 

The better way to do it, correctly, is to put it into a folder named CSS.

**Comment by haomateach** [comment]
You don't have a folder named **css**, then you should not write `css/styles.css`.
