### ISSUE TITLE
why ul and ol dont allow tags in them

### ISSUE THREAD

**Issue by kunalhanda111** [haomateach/webdev#21]
hi , i have been using image and table tag inside ol and ul . but when i am using validator to check the error it is saying that we cant use them in ol. does someone has any solution?
thank you
<img width="951" alt="Annotation (17)" src="https://user-images.githubusercontent.com/71738417/95633276-30ebb000-0a3c-11eb-90d7-b688c6c2264a.png">

**Comment by Waqar-Younis** [comment]
I faced the same problem, so I ended up removing the p tags and leaving them outside the Lists. And got the same results.

**Comment by haoma7** [comment]
<p> tag should not be used inside <ol> and <ul>

**Comment by haomateach** [comment]
p  tag should not be used inside ol and ul
