### ISSUE TITLE
Has anyone faced a problem with the second repository?  I got the link, but it does not work properly. Any solutions to the problem?

### ISSUE THREAD

**Issue by Waqar-Younis** [haomateach/webdev#22]

**Comment by haoma7** [comment]
What do you mean by second repository?

Also, It's better not to put the actual question body into the title. Title is title, it's different.

**Comment by haomateach** [comment]
What do you mean by the second repository?

Also, better not to put the actual question body into the title.

**Comment by Waqar-Younis** [comment]
Well, I found out in order for me to display the second page of my side through Github. I would have to make a second repository and get the link for that page. After that, I would have to put that link into my index.html page so navigation between the 2 pages can be easy.

**Comment by haomateach** [comment]
Are you talking about Assignment 1?

You just need one repo. One repo for each Assignment. You DON'T need  two repos for one individual assignment.

**Comment by Waqar-Younis** [comment]
ok, that makes sense.

Thank you,
