### ISSUE TITLE
Assignment2 Bootstrap

### ISSUE THREAD

**Issue by ppriya2** [haomateach/webdev#23]
My name is Priya and student id is 100400760
My course and section are INFO1213 S13

Hello, I am trying doing assignment 2 but the bootstrap I am adding in my code is not working. Can I have some suggestions?

**Comment by haomateach** [comment]
Could you elaborate on this question more? What have you done in order to link bootstrap?

**Comment by ppriya2** [comment]
I have added script in head section of the code to link bootstrap. Is that right?

**Comment by ppriya2** [comment]
And also, can I use the same html code that I have used in Assignment1?

**Comment by haoma7** [comment]
could you post the head section here?

**Comment by haomateach** [comment]
Could you post the head section here?

**Comment by ppriya2** [comment]
<head>
  <meta charset="utf-8">
  <title>Richard James</title>
  <link rel="stylesheet" href="./styles.css">
  
  <link href="https://fonts.googleapis.com/css2?family=Acme&family=Ranchers&family=Sacramento&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Dancing+Script:wght@500&family=Pacifico&display=swap" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>

**Comment by ppriya2** [comment]
<head>
  <meta charset="utf-8">
  <title>Richard James</title>
  <link rel="stylesheet" href="./styles.css">
  <link rel="icon" href="favicon.ico">
  <link href="https://fonts.googleapis.com/css2?family=Acme&family=Ranchers&family=Sacramento&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Dancing+Script:wght@500&family=Pacifico&display=swap" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>

**Comment by ppriya2** [comment]
I think I have to write these scripts in body tag and link to CSS in head tag. BTW thankyou for help Sir and please let me know if there is any other way of linking bootstrap.

**Comment by haomateach** [comment]
Yes, you are right. Also, see how I format your html code above with markdown.
