### ISSUE TITLE
Course number: INFO 1213 (R10) 

### ISSUE THREAD

**Issue by Simranpreet-web** [haomateach/webdev#26]
Course number:INFO 1213(R10)
Simranpreet kaur 
100391804

I have bought the book from udemy site and when i go on my learning button it's not showing there.
It's showing that i have not been enrolled in the course but i have already bought the book.

Can you please help me to get the book.

**Comment by haomateach** [comment]
Please attach a screenshot so that I can figure out for you. It shouldn't be this complicated. 

If you hover your mouse on the My learning Button, then click "Go to my learning" button at the bottom of the dropdown list, then you should see your course. Please let me know if you cannot see it.

**Comment by Simranpreet-web** [comment]
The Course is not showing up in this My Learning section.
________________________________

**Comment by haomateach** [comment]
Could you show me some screenshot of the website that you have purchased it? You can check your purchase history.
