### ISSUE TITLE
Course: INFO 1213: Web Application Development (R10)

### ISSUE THREAD

**Issue by AdrianPrograms** [haomateach/webdev#27]
Do we have to reuse our code from Assignment 1 or can we start from scratch but still have the same general format and functionality for Assignment 2? I think starting from scratch would be a bit better for me personally.

Finally, is linking bootstrap through cdn okay? It's technically external but I'm not quite sure if I should download bootstrap or just use the link in the tutorial.

**Comment by haomateach** [comment]
1. Assignment 2 needs to be based on Assignment 1. You can not make a completely irrelevant website in Assignment 2 from your Assignment 1. 
2. That's OK.
