### ISSUE TITLE
Bootstrap Grid System

### ISSUE THREAD

**Issue by ppriya2** [haomateach/webdev#29]
Hello, My name is Priya and Student Id is 100400760
my course and section are INFO1213 S13

When I add grid system in my code, the content hovers over the next part and hides under the third part of the website.
Can you tell me how to automatically add space when while using grid.
thankyou

**Comment by haomateach** [comment]
Hi Priya, u can send me the file via email. This kind of technical question cannot be answered if no original code is provided.
