### ISSUE TITLE
Github doesn't load CSS

### ISSUE THREAD

**Issue by HarshSidhu18** [haomateach/webdev#34]
Course number INFO 1213 and section S13
Harshveer Sidhu
I uploaded my assignment 2 Github repository a while ago but the site doesn't show any off my CSS(Background color, font style, etc). My file link has no slash infront of it ( css/styles.css ) so that isn't the problem. The site loads properly when I open it from the local files but not on Github. Is somebody else having the same issue?
![1](https://user-images.githubusercontent.com/72015216/97098797-6698b780-163e-11eb-9cbb-961b63425be1.png)
![2](https://user-images.githubusercontent.com/72015216/97098798-68fb1180-163e-11eb-839a-cb254326ff79.png)

**Comment by haomateach** [comment]
Guess you used absolute path, which make it work in your local env but not on github repo. Double-check your href value plz.

**Comment by HarshSidhu18** [comment]
Got it wotking, Thanks.
