### ISSUE TITLE
assignment 2

### ISSUE THREAD

**Issue by Bhavjot102** [haomateach/webdev#37]
info1213 web development
So I uploaded my file on github. but the images are not showing up.

**Comment by Taranpreet2** [comment]
info 1213 R10 Web development

I am facing the same issue with my assignment 2. All the CSS features are not showing up when I open it from my github link . Its everything right in the file explorer but when i zip that file to upload it on moodle, the CSS features are not even shown there in the file explorer.

**Comment by Taranpreet2** [comment]
@Bhavjot102  If you are done with your issue. Kindly help me get out of this.

**Comment by Bhavjot102** [comment]
@Taranpreet2 my issue has not been resolved.

**Comment by Bhavjot102** [comment]
@Taranpreet2 have you written css in front of styles.css

**Comment by Taranpreet2** [comment]
@Bhavjot102 yes, i have written it but still not working.

**Comment by haomateach** [comment]
Show me your file structure and the path value you used. Usually it's because your path is absolute, which make it work on your own pc and not on the host.

**Comment by Taranpreet2** [comment]
![Screenshot (769)](https://user-images.githubusercontent.com/71120133/97823135-0cbf6f80-1c86-11eb-88d9-472af1663d49.png)

**Comment by Taranpreet2** [comment]
@haomateach I have used the correct path i think. The problem is when i open the zipped file that i have uploaded on the moodle. It doesnot show any CSS features. It shows when i open the unzipped file.

**Comment by haomateach** [comment]
That's not a problem. You certainly should not open it when it's zipped. That's not a bug, it's a feature :)

**Comment by haomateach** [comment]
@Taranpreet2 You can send me the github link via Email.

**Comment by haomateach** [comment]
BTW, your script tags are put in the wrong place. Please refer to the bootstrap quick start guide.

**Comment by Taranpreet2** [comment]
@haomateach ohk, there isn't any issue with my github link. It works well :)
Thank you

**Comment by Taranpreet2** [comment]
@haomateach Thanks, I got it where to put the script tags :)
