### ISSUE TITLE
Assignment 3 question

### ISSUE THREAD

**Issue by Waqar-Younis** [haomateach/webdev#39]
INFO 1213 
S13

I have submitted assignment 3, but I have tried to get multiplication and division to show up. in the starting file. 
The only thing is when I use the starting file and fill in the missing information (*   /)  does not show up as a function when the site is running on the browser. To counter this I have tried to re-write the code and it worked fine, so I know the code I wrote in the missing places is correct. Please give me some feedback on if you would like me to submit the file with the re-written code or, the code you have provided us with?

**Comment by kunalhanda111** [comment]
I think we were supposed to complete the incomplete code . Not to modify it . And it worked for me .

**Comment by Waqar-Younis** [comment]
I didn't modify it, just for some reason if I use the code that has been given to us the (+ /) functions don't work at all 
it's kind of frustrating.

**Comment by Waqar-Younis** [comment]
so, the issue was I was using sublime, whereas I switched over to atom, and the issue was resolved instantly.
