### ISSUE TITLE
online classes

### ISSUE THREAD

**Issue by ppriya2** [haomateach/webdev#4]
**Course and Section Number**: web application development and design, S13
**Question**: are there going to be in-person online classes or not?
If Yes then how we can join them?

**Comment by rodrigomanriquep** [comment]
we not going to have online classes just as Bleakman said

**Comment by gunpreet007** [comment]
what about quizzes?

**Comment by ppriya2** [comment]
Thank you @Bleakman ,@rodrigomaniqueq for help.. and sorry for disturbing you again but may I know about Moodle? are the videos going to be posted on Moodle

**Comment by haomateach** [comment]
Moodle website: courses.kpu.ca

**Comment by ppriya2** [comment]
Thank you @haomateach
