### ISSUE TITLE
info 1213 s13

### ISSUE THREAD

**Issue by Waqar-Younis** [haomateach/webdev#42]
I have submitted assignment 4, but can you take a look at the app.js file since I keep getting the error Index of C:\ .

Thank you.

**Comment by shubham-klair** [comment]
Web Application Development Info 1213 Section R10

Hi , I have an issue regarding assignment 3 . Do we have to submit the zip file or just the normal calculator file ?

**Comment by HarshSidhu18** [comment]
The answer submission only accepts zip files.
