### ISSUE TITLE
INFO 1213 R10 A4 #46

### ISSUE THREAD

**Issue by Ravjot19** [haomateach/webdev#46]
I have been stuck on deploying Heroku  since last night. In the image I provided, the Heroku logs keeps showing two crashes and I can't seem to fix it. I think its from my "process.env.PORT" area because the process is coming up undefined. CAN someone Please help I haven't been able to resolve this for hours!!

![image](https://user-images.githubusercontent.com/71193087/99317140-65604200-281a-11eb-875a-bbc3a3f4728f.png)

**Comment by madmoney99** [comment]
What does your procfile point at?  Looks like it's calling index.js instead of app.js.

Did you install all the applicable modules with $npm install?

**Comment by Ravjot19** [comment]
I did install body-parser and express, I don't know why some of my codes are still undefined. Is there any I'm missing  that I haven't installed?

![image](https://user-images.githubusercontent.com/71193087/99337480-31dfe080-2837-11eb-9547-f8b53bf5020b.png)

**Comment by Ravjot19** [comment]
Could it be the environmental variables?

**Comment by madmoney99** [comment]
Feel free to take a look at my repository a4, it's functional and deployed.  Sometimes comparing code can help realize you're missing a comma or something simple like that

**Comment by Ravjot19** [comment]
I've noticed you had a server.js file. Is that necessary?

**Comment by Ravjot19** [comment]
I tried and wasn't able to find anything . I tried by adding "start": "node index.js" and it ended up duplicating my errors. 

![image](https://user-images.githubusercontent.com/71193087/99342428-ae2af180-2840-11eb-94c4-8446642bd24d.png)


I uploaded my files on GitHub. If you can check my repo files and notice anything that would be a great help.

**Comment by madmoney99** [comment]
Your procfile points at index.js.

You don't have an index.js.  You have an app.js, which is where the procfile should be pointing.  Check the path in your procfile and change it to 
```web: node app.js
```

I also notice you didn't upload the node_modules to your github.

**Comment by Ravjot19** [comment]
There was too many files so it did not let me upload. I don't know how to upload a folder  into the repo so I didn't bother. If you know, then I can upload them

**Comment by Ravjot19** [comment]
I changed it to app.js but it still gives my the two errors in the Heroku logs

**Comment by madmoney99** [comment]
Are you using Github desktop or CLI?  I've only used Github desktop as I use it for other coding stuff and it's easier to work with (for me at least) than using the command line.

**Comment by Ravjot19** [comment]
CMD

**Comment by madmoney99** [comment]
Then I'm of no help to you.  Not sure why it wouldn't just pick up the whole directory at once.  I'd suggest google for that, but hopefully the procfile change will at least you get you running in Hyper on your localhost:3000

**Comment by Ravjot19** [comment]
I've tried googling it and its referring to the environmental variables but I don't how to go about that. 

Thanks though, I appreciate the effort and advice.

**Comment by KAttafuah-Projects** [comment]
well i am still analyzing your code i had a different approach to working my stuff on heroku and hosting it there. if i do find the error id let you know
