### ISSUE TITLE
Assignment 5 due date?

### ISSUE THREAD

**Issue by AdrianPrograms** [haomateach/webdev#51]
INFO 1213: Web Application Development (R10)
ID: 100398503

I'm just double checking the due dates because I'm not sure if the current submission date, Nov 30th, is the proper due date for assignment 5 or not.

**Comment by haomateach** [comment]
Yes, but I will extend it, to allow as much time for you as possible.

**Comment by Bhavjot102** [comment]
@haomateach could you please check your email I have some problems with assignment 4.
