### ISSUE TITLE
Assignment 4 Bug Fixing Session

### ISSUE THREAD

**Issue by haomateach** [haomateach/webdev#54]
10:00 AM - 10:20 AM

10:20 AM - 10:40 AM

10:40 AM - 11:00 AM   Student: Bhavjot kaur 

11:00 AM - 11:20 AM   Student: Chandanpreet kaur 

11:20 AM - 11:40 AM   Student: Numan Syed

11:40 AM - 12:00 PM    Student: shubham-klair 

Please leave a comment below to indicate your preference for the time slot. If you cannot make it to any of those time slots, no worry, and we can schedule another session.

**Comment by shubham-klair** [comment]
Hi , my name is Shubham Klair in section R10. Can I have the last time slot (11:40-12) . Thankyou.

**Comment by NSyedQuestions** [comment]
Name: Numan Syed
Course: 1213 S13
Can i also pick the last one? (11:40 AM to 12:00 PM)
If not then 11:20 AM - 11:40 AM

**Comment by Chandanpreetkaur** [comment]
Hello, My name is Chandanpreetkaur from Info1213 R10. Can I have the (11:00-11:20) time slot?

**Comment by Bhavjot102** [comment]
INFO1213 R10
Hello, my name is Bhavjot kaur can I pick the (10:40-11:00) time slot.

**Comment by haomateach** [comment]
Please make sure to join the meeting on time.... thanks.
