### ISSUE TITLE
Assignment 4 Bug Fixing Session 2

### ISSUE THREAD

**Issue by haomateach** [haomateach/webdev#56]
7:00 PM - 7:20 PM  Student: Jagvir Kaur

7:20 PM - 7:40 PM

7:40 PM - 8:00 PM

8:00 PM - 8:20 PM Student: Waqar Younis

8:20 PM - 8:40 AM  

8:40 AM - 9:00 PM  Student: Taranpreet

Please leave a comment below to indicate your preference for the time slot. Thanks.

**Comment by Taranpreet2** [comment]
Taranpreet Kaur, 100394317
INFO 1213, R10
Hi professor, I want to choose the last time slot (8:40-9:00). Thank you.

**Comment by 100399925** [comment]
JAGVIR KAUR, 100399925
INFO 1213 S13
Hi professor!
I want to choose the time 7:00 PM TO 7:40 PM.

**Comment by Waqar-Younis** [comment]
Waqar Younis 100333129
INFO 1213 S13

I would like to choose from 8:00 pm to 8:20 pm.
Thank you
