### ISSUE TITLE
Quiz10 Question 1

### ISSUE THREAD

**Issue by ryanmend** [haomateach/webdev#58]
Web Application Development INFO 1213 R10

On Question 1 of Quiz10 I answered "Article" without the "s" because it didn't have S in the created collection name between the quotation marks but apparently the right answer was "Articles"? Was this a typographical error?

**Comment by madmoney99** [comment]
I had the exact same issue, and I have flagged the question on Moodle.

**Comment by haomateach** [comment]
@ryanmend @madmoney99  The question is correct. The name of the collection in the MongoDB will be automatically converted to be the plural format of the first argument of mongoose.model(). So the right answer is Articles, and you can test it.

**Comment by ryanmend** [comment]
It was completely my mistake. Thank you for the explanation.

**Comment by haomateach** [comment]
No prob. That's a tricky one.
