### ISSUE TITLE
A4, Final

### ISSUE THREAD

**Issue by ppriya2** [haomateach/webdev#59]
Hello Sir,

My name and id: Priya 100400760
Course and section: INFO1213 S13

1)
Sir, you said in one of your announcements that comments will be made on submitted A4. Can you please check my Assignment and update me on any possible changes I have to make in order to get good grades.

2)
Also, our final's date is given as **11 Dec, 2020**. what we have to cover for our final? and what would be the pattern of our final exam? Is it same as our midterm or something different?

**Comment by haomateach** [comment]
1. Yes, will do.
2. Just sent. It covers the whole semester.
