### ISSUE TITLE
Where to find the quiz

### ISSUE THREAD

**Issue by Samakira** [haomateach/webdev#6]
Web Application R10

the quiz was said to be released today, but i cant find it here or on moodle.

**Comment by BhavinRai** [comment]
also, assignment number one

**Comment by AdrianPrograms** [comment]
Yeah, I cannot seem to find it either. I will just be on standby for now.

**Comment by Taranpreet2** [comment]
Web Application Development R10
Taranpreet Kaur 100394317
When will the quiz and assignment for today be posted and whats the due date for those.

**Comment by AdrianPrograms** [comment]
> Web Application Development R10
> Taranpreet Kaur 100394317
> When will the quiz and assignment for today be posted and whats the due date for those.

He said due dates are usually on Sundays mornings for the assignments. However I don't see any of them so the due date is likely delayed.

**Comment by RoyZiJie** [comment]
Course and Section No.: Web Application R10
Student Name and ID: Zijie Zhang 100400070
Question: When will Quiz 1 be released and what's about

**Comment by Taranpreet2** [comment]
Thanks @AdrianPrograms , yeah i have listened it too that the due date of every quiz would be on sunday at 11:59 pm.

**Comment by haomateach** [comment]
Hi guys, it will be released soon. The due day will be next Sunday.

**Comment by prabhjot2022** [comment]
course and section number : Web application R10 
Student Name and ID: Prabhjot Preet Kaur, 100393983
@Samakira  He will upload quiz today and its deadline will on Sunday midnight.

**Comment by haomateach** [comment]
@prabhjot2022 Not this Sunday midnight... next one.

**Comment by prabhjot2022** [comment]
> @prabhjot2022 Not this Sunday midnight... next one.

@haomateach Thank you professor.

**Comment by Mehakdeepkaur4** [comment]
course and section number : Web application R10
Student Name and ID: Mehakdeep Kaur, 100396701
Quiz will be on moodle??

**Comment by haomateach** [comment]
Quiz has been uploaded.
