### ISSUE TITLE
INFO 1213 R10 A5 #60

### ISSUE THREAD

**Issue by Ravjot19** [haomateach/webdev#60]
Hi I'm trying to run my app.js but I keep getting this error. Any suggestions please? 

![image](https://user-images.githubusercontent.com/71193087/101125783-e9525200-35ae-11eb-87a2-c4ff86eb4204.png)

**Comment by ppriya2** [comment]
Hello
if your problem has not been solved yet. Try using this code in line 45
  const post = new Post ({
    title: req.body.postTitle,
    content: req.body.postBody
  });
also, instead of posts.push  try adding post.save {res.redirect("/")};

let me know if this works :)

**Comment by Ravjot19** [comment]
I tried using your code and it did not work. Keeps giving same reference Error.

![image](https://user-images.githubusercontent.com/71193087/101220171-11d35e00-363a-11eb-91b8-e776a92de7a0.png)


Also, I can't seem to access my blog page through my navbar. It shows page not found. Any Help Please?

![image](https://user-images.githubusercontent.com/71193087/101220332-5bbc4400-363a-11eb-9f10-059693474a08.png)

**Comment by ppriya2** [comment]
app.post("/compose", function(req, res){

  const post = new Post ({
    title: req.body.postTitle,
    content: req.body.postBody
  });

  post.save(function(err){
    if(!err){

  res.redirect("/Blog");

    }
  });

});

here is the full context try adding it in the same way. Also I think it's post not 'posts'

**Comment by ppriya2** [comment]
for navbar, in Partials>> header.ejs, in navbar section try this:
  <li id="home"><a href="/Blog">Blog</a></li>

[list item's href]

Hope this works.

**Comment by Ravjot19** [comment]
Thanks!! the code started my server but the page shows "Cannot Get /"

![image](https://user-images.githubusercontent.com/71193087/101265584-8078f000-36fc-11eb-958c-4c4e52c0bbb8.png)


For the navbar that you recommended, it didn't work unfortunately. 

I'm trying to access the page through my Index.html path. am I doing this wrong?

![image](https://user-images.githubusercontent.com/71193087/101265655-0b59ea80-36fd-11eb-883b-b07214ecda4f.png)


This is the outcome

![image](https://user-images.githubusercontent.com/71193087/101265670-23316e80-36fd-11eb-90bc-2f980dc93378.png)

**Comment by ppriya2** [comment]
in line 45, (app.js)
under app.get change res.render to compose.. not contact

for navbar,
change (home) list item back to "/" and instead add a new list item giving id "compose" and href "/compose". this is the path to your compose page.

because of time difference we have to wait more than 12 hours for each others reply... hope this doesn't effect your work much.
and Best of luck with the coding....if this code still doesn't work, don't hesitate to ask again. we'll work this out together :)

**Comment by Ravjot19** [comment]
I changed as you advised, but it didn't go through. Still  the same Error.

![image](https://user-images.githubusercontent.com/71193087/101312902-ca9bc780-3809-11eb-845a-c8d86e737bfc.png)


![image](https://user-images.githubusercontent.com/71193087/101312915-d6878980-3809-11eb-8e15-132a640cfcea.png)



Unfortunately yeah the replies aren't sooner, but its fine. Really appreciative and thankful for your help :))

**Comment by Ravjot19** [comment]
My other pages are working; compose, about, contact.

![image](https://user-images.githubusercontent.com/71193087/101313597-49453480-380b-11eb-956d-f595375e2597.png)

![image](https://user-images.githubusercontent.com/71193087/101313642-6da11100-380b-11eb-8b1d-aff3e7102017.png)

However, when I go for my blog page it shows this

![image](https://user-images.githubusercontent.com/71193087/101313679-86a9c200-380b-11eb-9fea-e6e851a4fefb.png)

What would you suggest?

**Comment by ppriya2** [comment]
LINE 26, app.js change  function (err, posts) not post.

error's also showing post not defined.

but the main problem is you don't have the post const. for mongoose model

**Comment by Ravjot19** [comment]
I am following the Udemy video, at this stage I tried running "node app.js" and this was the outcome.

![image](https://user-images.githubusercontent.com/71193087/101427172-3f770c00-38b3-11eb-88be-c87ace4f14af.png)


I didn't create a new database. I had just put  in "postsdb" thinking that is the existing one that links to my posts from the blog. Do I need to create a new DB? or is there a way to link it to the blog posts? I'm a bit confused.

**Comment by haomateach** [comment]
?Hi Ravjot,


Your case seems complicated, I think we better talk about it over the Zoom.



------------------------------------------------------------------------
Hao Ma, Ph.D., Faculty Member,
Department of Computer Science and Information Technology
School of Business, Kwantlen Polytechnic University
---------------------------------------------------------------------
________________________________

**Comment by ppriya2** [comment]
line 24 ; is missing at the end 
line 66 /posts/:postName  

try this and further professor is also expecting you to attend an in person session. 
Best of luck for your study.

**Comment by Ravjot19** [comment]
I was able to make it work with the professor thankfully, but I am trying to access my blog page through  my index.html navbar. However it takes me to my local disk page.

![image](https://user-images.githubusercontent.com/71193087/101442146-88d55480-38cf-11eb-9d0f-5c741c5450d7.png)


![image](https://user-images.githubusercontent.com/71193087/101442174-94288000-38cf-11eb-9996-1e2f531a3a06.png)

What do I need to change in my href?

**Comment by haomateach** [comment]
I think you may want to re-watch sections about the basics of back-end development.


I think you did not access the index.html from localhost:3000, instead you just open it using browser.


This is a mistake that shows your weak understanding of those sections. Please consider re-watching it.



------------------------------------------------------------------------
Hao Ma, Ph.D., Faculty Member,
Department of Computer Science and Information Technology
School of Business, Kwantlen Polytechnic University
---------------------------------------------------------------------
________________________________

**Comment by Ravjot19** [comment]
The highlighted code is preventing me from starting the server. 

![image](https://user-images.githubusercontent.com/71193087/101555423-7dd10180-396d-11eb-8d12-615742e563d9.png)


Any suggestions?

**Comment by haomateach** [comment]
?Have you compared your code with the solution code?



------------------------------------------------------------------------
Hao Ma, Ph.D., Faculty Member,
Department of Computer Science and Information Technology
School of Business, Kwantlen Polytechnic University
---------------------------------------------------------------------
________________________________

**Comment by Ravjot19** [comment]
Yes, on the right side I have opened the solution code and for some reason still doesn't go through.

![image](https://user-images.githubusercontent.com/71193087/101755213-7868d980-3a89-11eb-84db-fd6cb13c0ecf.png)

**Comment by Ravjot19** [comment]
I was able to resolve my last problem, but what I am dealing with now is the compose. When I try to write a new Post, I get an error that refers to my line 66, but the code is same as the solution.

![image](https://user-images.githubusercontent.com/71193087/101966097-b1a96280-3bcb-11eb-9a67-f61430214f11.png)


![image](https://user-images.githubusercontent.com/71193087/101966124-cbe34080-3bcb-11eb-8a56-8b02a5335117.png)

Help Please

**Comment by Ravjot19** [comment]
Nevermind I got it to work, I had to remove the 's'

**Comment by Ravjot19** [comment]
For Deploying the site to Heroku, is the procedure the same as assignment 4 which was referring to section 20-251 Or is it a different procedure?

**Comment by haomateach** [comment]
Yes

**Comment by Ravjot19** [comment]
I tried deploying on to Heroku and it shows an "Internal Server Error". I checked the logs and the following came up.

![image](https://user-images.githubusercontent.com/71193087/102001716-f99eb700-3ca9-11eb-9994-c70c94635cf9.png)


Any Solutions?

**Comment by haomateach** [comment]
Please check the line 7 of your home.ejs file. You can see the error from the error message.
When you see error, don't panic, just patiently read the error message, and locate the error.
