### ISSUE TITLE
Discussion Participation AND pre-A5 marks

### ISSUE THREAD

**Issue by ppriya2** [haomateach/webdev#68]
Hi @haomateach  Sir

I'm Priya id: 100400760
Course and Section: Info 1213 S13

Quiz 1 to 5's marks are not showing. Can you Please update the settings so, we can confirm our pre-A5 marks.
And may I ask why my name is not in Discussion participation list?
Thank you.

**Comment by Bhavjot102** [comment]
Hi @haomateach 
I actually have the same question . Why my name is not there?

**Comment by haomateach** [comment]
@ppriya2 @Bhavjot102  Could you send me the link of the thread where you helped another student with his/her question? Apologies if I missed it.

**Comment by Bhavjot102** [comment]
https://github.com/haomateach/webdev/issues/37#issuecomment-720186272
I do not know if this was enough help but I did.

**Comment by haomateach** [comment]
@Bhavjot102  added!
