### ISSUE TITLE
link -issue

### ISSUE THREAD

**Issue by ppriya2** [haomateach/webdev#69]
hi @haomateach sir
my name and id: Priya 100400760
course and section: INFO 1213 S13

this is the link, about the mentions in the previous issue. hope this help.
https://github.com/haomateach/webdev/issues/60#issue-756816278

Thank you

**Comment by haomateach** [comment]
Thanks!

**Comment by haomateach** [comment]
@ppriya2 Please leave the info on that thread. Thanks.

**Comment by ppriya2** [comment]
Thank you Sir
