### ISSUE TITLE
Is the quiz on moodle? 

### ISSUE THREAD

**Issue by Joshua-Pineda** [haomateach/webdev#7]
Course and Section No.: Web Application S13
Student Name and ID: Joshua Pineda 100381835
Question: Is the quiz going to be on moodle or Github?

**Comment by Taranpreet2** [comment]
Course and section no: Web application R10
Student name and ID: Taranpreet Kaur, 100394317
Github is only for discussion i think. Quiz would probably be posted on moodle.

**Comment by haomateach** [comment]
@Joshua-Pineda  Moodle.

**Comment by Joshua-Pineda** [comment]
Thank you!

**Comment by Mehakdeepkaur4** [comment]
Course and section no: Web application R10
Student name and ID: Mehakdeep Kaur Kaur, 100396701


When the quiz will be posted??
