### ISSUE TITLE
Course and Section NO : Web Development R10

### ISSUE THREAD

**Issue by Simranpreet-web** [haomateach/webdev#8]
When will the quiz be uploaded ?

**Comment by BhavinRai** [comment]
I still do not see the assignment and quiz, is the assignment and quiz being canceled?

**Comment by AdrianPrograms** [comment]
Hi everyone, he said that the assignment and the quiz will be delayed and the new due date will be on Sunday next week.

Right now, we don't know when it will be uploaded.

**Comment by haomateach** [comment]
Sorry for the delay, the new video editing softwares failed me and I need to record a new one.  It will be uploaded this Monday night. Quiz has been uploaded.
